-- return function(client, bufnr)
--
-- require("astronvim.utils.lsp").on_attach(client, bufnr)
-- local rt = require "rust-tools"
--
-- local utils = require "astronvim.utils"
--
-- utils.set_mappings({
--   n = {
--     ["<leader>r"] = { name = " Rust Tools" },
--     ["<leader>rr"] = { rt.hover_actions.hover_actions, desc = "Rust Hover Actions" },
--     ["<leader>ra"] = { rt.code_action_group.code_action_group, desc = "Rust Code Actions" },
--   },
-- }, { buffer = bufnr })
-- end
